Оптимизируй это (Часть 2)
htmlacademy-react/1551181-six-cities-7 pull request #14
Opened 2021-08-01 09:52 UTC by FurmanT

2021-08-01 12:06 UTC, bini1988 requested changes
Отлично справляешься, нужно немного поправить страницу `Main` и перенесте в нее вестку из комопнента `MainEmpty` это комопнент в целом дублирует и `Main` не нужен.

2021-08-01 12:06 UTC, bini1988 commented on project/src/store/api-actions.js
> +export const getOfferComments = (id) => (dispatch, _getState, api) => {
`getOfferComments` очень просто спутать с redux селектором, лучше избегать такого и именовать экшены, например, как `loadOfferComments` или `fetchOfferComments`

2021-08-01 12:06 UTC, bini1988 commented on project/src/store/api-actions.js
> +      dispatch(ActionCreator.loadFavoriteOffers(adaptOffersToClient(data)));
Аналогично, единообразие то что отличает хорошего программиста:
```js
getFavoriteOffers() // это селоктор он возвращает данные
loadFavoriteOffers() // это санк он запрашивает данные
setFavoriteOffers() // это экшен он сохраняет полученные данные в store
```
Определи единый стиль именования селекторов, санков и экшенов и используй его в проекте и колеги будут тебе бесконечно благодарны

2021-08-01 12:41 UTC, FurmanT commented on project/src/components/favorites/favorites.jsx
> +                                  <Link to="/" onClick={(e) => e.preventDefault()}>
есть по клику по названию предложения

2021-08-02 17:18 UTC, bini1988 requested changes
> Клик по email пользователя в шапке выполняет переход на страницу «Favorites» (/favorites).

Сейчас при первом логине, клик по email пользователя в шапке выполняет переход на страницу логина

> Клик по заголовку карточки выполняет переход на страницу с подробной информацией о предложении.

Из-за кода ниже не отображаются предложения у которых еще нет комментариев, такого быть не должно:

```js
  if (!offer || nearby.length === 0 || comments.length === 0) {
    return null;
  }
```
> Если предложения отсутствуют, то в списке отображается надпись «No places to stay available», а вместо карты отображается статичное изображение. См. пример соответствующей страницы макета.

Код ломается если сервер вернет пустой список предложений, можно протестить кодом:

```js
export const fetchOffersList = () => (dispatch, _getState, api) => (
  api.get(APIRoute.HOTELS)
    .then(({data}) => {
      dispatch(ActionCreator.loadOffers(adaptOffersToClient([])));
    })
    .catch(() => {
      dispatch(ActionCreator.setStatusLoadOffers(RESULT.ERROR));
    })
);
```

> На странице предложения (/offer) представлена расширенная информация об объекте для аренды: Фотографии. Выводится до 6-ти изображений.

> Под списком отзывов отображается карта с предложениями неподалёку. На карте отмечено не больше 3-х предложений неподалёку и маркер текущего предложения. Маркеры предложений выделены синим. **Маркер текущего предложения выделен оранжевым.** Другая функциональность для карты с предложениями неподалёку не предусмотрена.

> На страницу выводится не больше 10 отзывов.

Надо ограничить количество выводимых отзывов.

> В поле «логин» должен вводится корректный email. Пароль не может состоять из одних пробелов.

Нужно выводить сообщение если при отправки формы произошла ошибка авторизации

2021-08-02 19:10 UTC, merged